name: Merge to Main

on:
  push:
    branches:
      - main
    paths:
      - tests/**
      - pipeline_flow/**
      - poetry.lock
      - pyproject.toml
      - ruff.toml
      - pyrightconfig.json

    workflow_dispatch:


permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "2.1.1"
  POETRY_URL: https://install.python-poetry.org


jobs:

  setup:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Install Poetry  ${{ env.POETRY_VERSION }}
        run: curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}

      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
          cache-dependency-path: ${{ github.workspace }}/poetry.lock 

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --all-extras

      - name: Lint with Ruff and Pyright
        run: |
          make build
  
      - name: Run tests
        run: |
          poetry run pytest tests/unit tests/integration
