name: Merge to Main

on:
  push:
    branches:
      - main
    workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:

  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python
          poetry config virtualenvs.in-project true
          poetry install --all-extras
          poetry run pip install -U pip

      - name: Upload virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: .venv


  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: .venv


      - name: Lint with Ruff and Pyright
        run: |
          source .venv/bin/activate
          make build
  
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: .venv

    
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run pytest tests/unit tests/integration
